---
- hosts: webservers
  become: yes
  tasks:

    - name: update php repository
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: install packages
      apt: name={{ item }} update_cache=true state=present
      with_items:
        - git
        - mcrypt
        - nginx
        - postgresql
        - php7.0
        - php7.0-cli
        - php7.0-curl
        - php7.0-fpm
        - php7.0-json
        - php7.0-mcrypt
        - php7.0-mbstring
        - php7.0-pgsql
        - php7.0-xml
        - php7.0-zip
      tags: packages

    - name: create /var/www/ directory
      file: dest=/var/www/ state=directory owner=vagrant group=vagrant mode=0755

    - name: download composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer
      tags: composer

    - name: install composer
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer
      tags: composer

    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer
      tags: composer

    - name: make composer executable
      file:
        path: /usr/local/bin/composer
        mode: a+x
        state: file
      tags: composer

    - name: ensure php7.0-fpm cgi.fix_pathinfo=0
      lineinfile: dest=/etc/php/7.0/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0
      notify:
        - restart php7.0-fpm
        - restart nginx

    - name: Configure nginx
      template: src=files/nginx.conf dest=/etc/nginx/sites-available/default
      notify:
        - restart php7.0-fpm
        - restart nginx
      tags: nginx

  handlers:
    - name: restart php7.0-fpm
      service: name=php7.0-fpm state=restarted

    - name: restart nginx
      service: name=nginx state=restarted
